### ISSUE TITLE
How to force users to login/register?

### ISSUE THREAD

**Issue by teriame** [CodelightStudios/Android-Smart-Login#13]
Hi,

I have an app where users have to login/register in order to use the app.
Is there a way to disable the up button and change the back button to leaving the app?
Restarting the intent when the user pushes up/back is ugly.

Thanks!

**Comment by kalyandechiraju** [comment]
Hi @teriame the current version of Smart Login doesn't support this feature. Instead, you can have a landing page for the app with a login button. Since the login activity is started for a result, you need to have a calling activity to handle your app's logic. 

But will consider this feature to be added in the next release.

**Comment by kalyandechiraju** [comment]
Hi @teriame You can achieve this by having a check in the entry activity for the logged in user.

```java
SmartUser currentUser = UserSessionManager.getCurrentUser(context);
if(currentUser != null){
    //Proceed into the app
} else {
   //call the login activity
}
```
