### ISSUE TITLE
Modification 

### ISSUE THREAD

**Issue by kkrishnan90** [CodelightStudios/Android-Smart-Login#17]
Hi, 
Thanks a ton for such an amazing library. It's really darn useful and shaves a lot of time for developers to include social logins. Just one query. Am I allowed to make modifications in your library like changing the text views color ,etc? By the way, I have included your project as a library in my android. So it goes with direct modification of your source code.. Am I allowed to do it ?

**Comment by kalyandechiraju** [comment]
Hi @kkrishnan90 I am happy that this library helped you. My goal with this library is to reduce the development time and simplify development of Android Apps by automating the repetitive work. 

**Yes**, you can edit this library for your need. `Also your contribution to this library is welcome.` Please do share your modifications with us so that we can include into the core library if it's useful for others.

Also look into this #5.

**Comment by kalyandechiraju** [comment]
Also remember that in the current version of the Master Branch, there are issues with the `Google Login`. Am looking into fixing it. Meanwhile you can use the version specified in the ReadME file.

**Comment by kkrishnan90** [comment]
Thanks a lot mate ! I'll look into this and I'll do what best I can. I'll also help you in creating next release with custom login interface.

**Comment by kalyandechiraju** [comment]
Cheers!!
