### ISSUE TITLE
Get authToken from Google/Facebook login

### ISSUE THREAD

**Issue by laubed** [CodelightStudios/Android-Smart-Login#23]
Is it possible to get the authToken/authCodes from the oauth with google and facebook?

**Comment by freak005** [comment]
hey! Is it possible?

**Comment by kalyandechiraju** [comment]
Hi @laubed @freak005  Take a look into [SmartLoginActivity](https://github.com/CodelightStudios/Android-Smart-Login/blob/master/smartloginlibrary/src/main/java/studios/codelight/smartloginlibrary/SmartLoginActivity.java). In the method, doFacebookLogin(), `loginResult.getAccessToken()` is used to get the user information through graph request. So tweaking it a little bit we can get the accesstoken out. In the next version, I will add token property for the user object so that its easy to get it out.

**Comment by kalyandechiraju** [comment]
@laubed @freak005 The library is updated to version 1.x with AccessToken added as SmartUser property. Check out README for more details. Project Wiki will be ready soon.
