### ISSUE TITLE
Pls Create Good sample app.

### ISSUE THREAD

**Issue by naguchennai** [CodelightStudios/Android-Smart-Login#26]
Sample not work .. No showing proper error report .. it just say "Something Wrong" How we can find error? sample only  have layout. Developer looking library for make work easy.. i am right?

**Comment by kalyandechiraju** [comment]
@naguchennai Why can't you fix it and send a pull request instead of a funny comment ? !!

**Comment by kalyandechiraju** [comment]
Hi @naguchennai I am currently writing a new version of the library with the option of passing your own layout. This would change all the current road blocks in the current version. Due to layout inflation on different UI thread am stuck in an issue. Trying different ways. Once its fixed, I will push right away with good sample app and proper wiki. 
Thanks for trying out this library.

**Comment by kalyandechiraju** [comment]
@naguchennai The sample app is updated with new version library.
