### ISSUE TITLE
Problem with result of the custom login method

### ISSUE THREAD

**Issue by agenco12** [CodelightStudios/Android-Smart-Login#30]
![schermata 2016-09-21 alle 13 46 30](https://cloud.githubusercontent.com/assets/9123045/18709758/f247b9f2-8001-11e6-8034-1b2241076ace.png)
Hello @kalyandechiraju , I have a question about your Android Smart Login Library.  I'm  developing my customSignup method and I wanted to know what is the return value for? and where is it used?

**Comment by kalyandechiraju** [comment]
Hi @agenco12 that boolean return is intended to let the library screen know if the user login/signup has completed successfully or not so that it can come back to the caller activity with a result (basically to onActivityResult method)

**Comment by agenco12** [comment]
Thank you very much, i have another problem and I post this on stackoverflow, can you help me ? 

http://stackoverflow.com/questions/39626748/synchronous-request-with-volley-android

**Comment by kalyandechiraju** [comment]
@agenco12 Sure! will look into that.

**Comment by kalyandechiraju** [comment]
@agenco12 As per the description what I understood is that the code inside the CustomSignIn method makes a network call asynchronously using volley which will set the session info later when the request is complete. 

So when you say 

```java
AppController.getInstance().addToRequestQueue(strReq); // Dispatch async call

  if(SessionHandler.logged){ // This happens in the current UI thread (which be returning the default value or an exception
        return true;
    } else {
        return false;
    }
```

Since it is user login functionality, why do you want it in an async manner? Better way would be:
show an indeterminate progress dialog and make the call synchronously and return the value.

Correct me if my understanding is wrong.
