### ISSUE TITLE
ETA on improved login page

### ISSUE THREAD

**Issue by ldimitroff** [CodelightStudios/Android-Smart-Login#31]
Hi there, just to know. Is there any ETA on when the login page and gradle dependency will be available? Just to know, cause I'm using the library as module from my project.
Is there anything that I can help with?
Thanks

**Comment by kalyandechiraju** [comment]
Hi, @ldimitroff I would be happy to accept any pull requests. Currently, the library is tightly coupled with the UI. Decoupling it and providing just plain APIs is the plan so that it can be used in any situation. I have made some progress in this. I am planning to push it in a couple of weeks (in a busy schedule, maybe expect an update in 2nd week of October). Once  that is pushed, you can improve it and help me out. 

Thank you again for support.
